\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename readme.info
@settitle Perl Verilog::Pli Installation
@c %**end of header

@c $Id: readme.texi,v 1.12 2004/01/27 19:11:43 wsnyder Exp $
@c DESCRIPTION: TexInfo: DOCUMENT source run through texinfo to produce README file
@c Use 'make README' to produce the output file

@node Top, Copyright, (dir), (dir)

This is the Verilog::Pli Perl Package.

@menu
* Copyright::                   
* Description::                 
* Obtaining Distribution::      
* Supported Systems::           
* Installation::                
@end menu

@node Copyright, Description, Top, Top
@section Copyright

This package is Copyright 1998-2004 by Wilson Snyder @email{wsnyder@@wsnyder.org}.

You may distribute under the terms of either the GNU General Public
License or the Perl Artistic License, as specified in the Perl README
file.

This code is provided with no warranty of any kind, and is used entirely at
your own risk.

@node Description, Obtaining Distribution, Copyright, Top
@section Description

This package provides access to Verilog PLI routines from within Perl.

@example
  $NET@{a_signal@} = 1
  do_stop();
@end example

See @samp{man Verilog::Pli} after installation.

@node Obtaining Distribution, Supported Systems, Description, Top
@section Obtaining Distribution

The latest version is available at 
@uref{http://www.perl.org/CPAN/}

Download the latest package from that site, and decompress.
@samp{gunzip Verilog-Pli_version.tar.gz ; tar xvf Verilog-Pli_version.tar}

@node Supported Systems, Installation, Obtaining Distribution, Top
@section Supported Systems

This version of Verilog::Pli has been built and tested on:

@itemize @bullet
@item sparc-sun-solaris2.6
@item i686-linux-2.2.5
@end itemize

It should run on any system with Perl and VCS or other Verilog simulator
with minor porting.

@node Installation, Interpreter, Supported Systems, Top
@section Installation

@enumerate
@item
@code{cd} to the directory containing this INSTALL notice.

@item
Type @samp{perl Makefile.PL} to configure Verilog::Pli for your system.

@item
Type @samp{make} to compile Verilog::Pli.  If you are not using VCS
and get a error about vcsuser.h not being found, you may need to
change the include of vcsuser.h in perl_cmd.c to veriuser.h.

@item
Type @samp{make install} to install the programs and any data files and
documentation.

@item
If you have VCS, @samp{cd example ; make} to see an example.

@end enumerate

@node Interpreter,  , Installation, Top
@section Interpreter

You will need a perl interpreter inside your simulator to make this
package useful.  A example verilog file, pli C wrapper and all is inside
the example directory.  This example uses VCS, but will work with minor
modifications with Verilog-XL and other Verilog simulators with a PLI.

@enumerate
@item
cd example

@item
make

@end enumerate

Thanks to Tom Kraljevic @email{tomk@@titanic.Abrizio.COM} for this
example.


